![Finance Toolkit](https://github.com/JerBouma/FinanceToolkit/assets/46355364/198d47bd-e1b3-492d-acc4-5d9f02d1d009)

The Finance Toolkit can take in any dataset which means it works very well with the software and APIs from any other provider let is be Intrinio, OpenBB, Yahoo Finance, Quandl, etc. For this illustration, I have collected custom statements and have imported them as a CSV file but as you can imagine this would also work with direct API calls. This dataset is obtained from Yahoo Finance, which can be collected via `yfinance`. Note that the `yfinance` library is not part of the Finance Toolkit and needs to be installed separately.

In [1]:
import pandas as pd
from financetoolkit import Toolkit

First, let's read in the custom dataset obtained from Yahoo Finance.

In [2]:
# Balance Sheet Statements
tsla_balance = pd.read_csv('external_datasets/TSLA_balance.csv', index_col=0)
googl_balance = pd.read_csv('external_datasets/GOOGL_balance.csv', index_col=0)

# Income Statements
tsla_income = pd.read_csv('external_datasets/TSLA_income.csv', index_col=0)
googl_income = pd.read_csv('external_datasets/GOOGL_income.csv', index_col=0)

# Cash Flow Statements
tsla_cash = pd.read_csv('external_datasets/TSLA_cash.csv', index_col=0)
googl_cash = pd.read_csv('external_datasets/GOOGL_cash.csv', index_col=0)

# Show one of the datasets
tsla_income

,ttm,2022-12-31,2021-12-31,2020-12-31,2019-12-31
Breakdown,,,,,
Total revenue,9.402800e+10,8.146200e+10,5.382300e+10,3.153600e+10,2.457800e+10
Cost of revenue,7.382500e+10,6.060900e+10,4.021700e+10,2.490600e+10,2.050900e+10
Gross profit,2.020300e+10,2.085300e+10,1.360600e+10,6.630000e+09,4.069000e+09
Research development,3.257000e+09,3.075000e+09,2.593000e+09,1.491000e+09,1.343000e+09
Selling general and administrative,4.260000e+09,3.946000e+09,4.517000e+09,3.145000e+09,2.646000e+09
Total operating expenses,7.517000e+09,7.021000e+09,7.110000e+09,4.636000e+09,3.989000e+09
Operating income or loss,1.268600e+10,1.383200e+10,6.496000e+09,1.994000e+09,8.000000e+07
Interest expense,1.430000e+08,1.910000e+08,3.710000e+08,7.480000e+08,6.850000e+08
Total other income/expenses net,1.190000e+08,-2.190000e+08,1.620000e+08,-1.220000e+08,-1.040000e+08
Income before tax,1.335600e+10,1.371900e+10,6.343000e+09,1.154000e+09,-6.650000e+08
Income tax expense,1.165000e+09,1.132000e+09,6.990000e+08,2.920000e+08,1.100000e+08
Income from continuing operations,1.219100e+10,1.258700e+10,5.644000e+09,8.620000e+08,-7.750000e+08
Net income,1.222200e+10,1.258300e+10,5.519000e+09,6.900000e+08,-8.620000e+08
Net income available to common shareholders,1.223500e+10,1.258300e+10,5.519000e+09,6.900000e+08,-8.620000e+08
Basic average shares,3.160500e+09,3.130000e+09,2.958000e+09,2.799000e+09,2.661000e+09
Diluted average shares,3.477000e+09,3.475000e+09,3.387000e+09,3.249000e+09,2.661000e+09
EBITDA,NaN,1.765700e+10,9.625000e+09,4.224000e+09,2.174000e+09
Basic EPS,3.880000e+00,4.020000e+00,1.870000e+00,2.500000e-01,-3.300000e-01
Diluted EPS,3.510000e+00,3.620000e+00,1.630000e+00,2.100000e-01,-3.300000e-01

Then, it's time to acquire the normalization files via the Toolkit to be used to normalize the results.

In [3]:
Toolkit("TSLA").get_normalization_files()

Files are being saved to C:\Users\hp\Downloads

With this information, by copying over each name as defined by Yahoo Finance for the balance, income and cash flow statements as also defined above, the normalisation files can be filled. The result can be found within the `examples/external_datasets` folder of the project as found [here](https://github.com/JerBouma/FinanceToolkit/tree/main/examples). Now it's time to convert each dataset in the right format.

In [4]:
from financetoolkit.base import helpers

balance_sheets = helpers.combine_dataframes(
    {
        "TSLA": tsla_balance,
        "GOOGL": googl_balance,
    },
)
income_statements = helpers.combine_dataframes(
    {
        "TSLA": tsla_income,
        "GOOGL": googl_income,
    },
)
cash_flow_statements = helpers.combine_dataframes(
    {"TSLA": tsla_cash, "GOOGL": googl_cash},
)

# The TTM column is dropped as it contains only a portion of this year
income_statements = income_statements.drop(columns=["ttm"])
cash_flow_statements = cash_flow_statements.drop(columns=["ttm"])

# Show the Results
balance_sheets

                                                     2022-12-31  \
      Breakdown
GOOGL Cash and cash equivalents                   21879000000.0
      Other short-term investments                91883000000.0
      Total cash                                 113762000000.0
      Net receivables                             40258000000.0
      Inventory                                    2670000000.0
...                                                         ...
TSLA  Common stock                                    3000000.0
      Retained earnings                           12885000000.0
      Accumulated other comprehensive income       -361000000.0
      Total stockholders' equity                  44704000000.0
      Total liabilities and stockholders' equity  82338000000.0

                                                     2021-12-31  \
      Breakdown
GOOGL Cash and cash equivalents                   20945000000.0
      Other short-term investments               118704000000.0
      Total cash                                 139649000000.0
      Net receivables                             39304000000.0
      Inventory                                    1170000000.0
...                                                         ...
TSLA  Common stock                                    1000000.0
      Retained earnings                             331000000.0
      Accumulated other comprehensive income         54000000.0
      Total stockholders' equity                  30189000000.0
      Total liabilities and stockholders' equity  62131000000.0

                                                     2020-12-31     2019-12-31
      Breakdown
GOOGL Cash and cash equivalents                   26465000000.0  18498000000.0
      Other short-term investments               110229000000.0 101177000000.0
      Total cash                                 136694000000.0 119675000000.0
      Net receivables                             30930000000.0  25326000000.0
      Inventory                                     728000000.0    999000000.0
...                                                         ...            ...
TSLA  Common stock                                    1000000.0            0.0
      Retained earnings                           -5399000000.0  -6083000000.0
      Accumulated other comprehensive income        363000000.0    -36000000.0
      Total stockholders' equity                  22225000000.0   6618000000.0
      Total liabilities and stockholders' equity  52148000000.0  34309000000.0

[65 rows x 4 columns]

With this done, it's now time to initialize the Toolkit and start using the Finance Toolkit with these custom datasets. By looking at the Balance Sheet Statement you can see that the column names have changed to the normalisation files.

**Note:** It is important to always ensure that dates go from left to right. For example this dataset starts at 2022 and ends at 2019. This should be reversed to accommodate shifting the DataFrames accordingly throughout the Toolkit. E.g. for growth metrics or specific ratios that require current and past values.

In [5]:
# initialize the Toolkit
companies = Toolkit(
    tickers=["TSLA", "GOOGL"],
    balance=balance_sheets,
    income=income_statements,
    cash=cash_flow_statements,
    format_location="external_datasets",
    reverse_dates=True, # Important when the dates are descending
) 

# Show the Balance Sheet
companies.get_balance_sheet_statement()

                                                         2019           2020  \
      Breakdown
GOOGL Cash and Cash Equivalents                 18498000000.0  26465000000.0
      Short Term Investments                   101177000000.0 110229000000.0
      Cash and Short Term Investments          119675000000.0 136694000000.0
      Accounts Receivable                       25326000000.0  30930000000.0
      Inventory                                   999000000.0    728000000.0
      Other Current Assets                       4412000000.0   5490000000.0
      Total Current Assets                     152578000000.0 174296000000.0
      Long Term Investments                     13078000000.0  20703000000.0
      Goodwill                                  20624000000.0  21175000000.0
      Intangible Assets                          1979000000.0   1445000000.0
      Other Fixed Assets                         2342000000.0   3953000000.0
      Fixed Assets                             123331000000.0 145320000000.0
      Total Assets                             275909000000.0 319616000000.0
      Accounts Payable                           5561000000.0   5589000000.0
      Tax Payables                                274000000.0   1485000000.0
      Deferred Revenue                           1908000000.0   2543000000.0
      Deferred Revenue                            358000000.0    481000000.0
      Other Current Liabilities                  9405000000.0  10409000000.0
      Total Current Liabilities                 45221000000.0  56834000000.0
      Long Term Debt                             4554000000.0  13932000000.0
      Deferred Tax Liabilities                   1701000000.0   3561000000.0
      Other Non Current Liabilities              2534000000.0   2269000000.0
      Total Non Current Liabilities             29246000000.0  40238000000.0
      Total Liabilities                         74467000000.0  97072000000.0
      Common Stock                              50552000000.0  58510000000.0
      Retained Earnings                        152122000000.0 163401000000.0
      Accumulated Other Comprehensive Income    -1232000000.0    633000000.0
      Total Equity                             201442000000.0 222544000000.0
      Total Liabilities and Shareholder Equity 275909000000.0 319616000000.0
TSLA  Cash and Cash Equivalents                  6268000000.0  19384000000.0
      Short Term Investments                              NaN            NaN
      Cash and Short Term Investments            6268000000.0  19384000000.0
      Accounts Receivable                        1324000000.0   1886000000.0
      Inventory                                  3552000000.0   4101000000.0
      Other Current Assets                                NaN            NaN
      Total Current Assets                      12103000000.0  26717000000.0
      Goodwill                                    198000000.0    207000000.0
      Intangible Assets                           339000000.0    313000000.0
      Other Fixed Assets                         1077000000.0   1536000000.0
      Fixed Assets                              22206000000.0  25431000000.0
      Total Assets                              34309000000.0  52148000000.0
      Accounts Payable                           3771000000.0   6051000000.0
      Deferred Revenue                           1889000000.0   2210000000.0
      Deferred Revenue                           1207000000.0   1284000000.0
      Other Current Liabilities                   317000000.0    241000000.0
      Total Current Liabilities                 10667000000.0  14248000000.0
      Long Term Debt                            11634000000.0   9607000000.0
      Deferred Tax Liabilities                            NaN    151000000.0
      Other Non Current Liabilities              2691000000.0   3330000000.0
      Total Non Current Liabilities             15532000000.0  14221000000.0
      Total Liabilities                         26199000000.0  28469000000.0
      Common Stock                                        0.0      1000000.0
      Retained Earnings                         -6083000000.0  -5399000000.0
      Accumulated Other Comprehensive Income      -36000000.0    363000000.0
      Total Equity                               6618000000.0  22225000000.0
      Total Liabilities and Shareholder Equity  34309000000.0  52148000000.0
      Short Term Debt                            1785000000.0   2132000000.0

                                                         2021           2022
      Breakdown
GOOGL Cash and Cash Equivalents                 20945000000.0  21879000000.0
      Short Term Investments                   118704000000.0  91883000000.0
      Cash and Short Term Investments          139649000000.0 113762000000.0
      Accounts Receivable                       39304000000.0  40258000000.0
      Inventory                                  1170000000.0   2670000000.0
      Other Current Assets                       7054000000.0   8105000000.0
      Total Current Assets                     188143000000.0 164795000000.0
      Long Term Investments                     29549000000.0  30492000000.0
      Goodwill                                  22956000000.0  28960000000.0
      Intangible Assets                          1417000000.0   2084000000.0
      Other Fixed Assets                         5361000000.0   6623000000.0
      Fixed Assets                             171125000000.0 200469000000.0
      Total Assets                             359268000000.0 365264000000.0
      Accounts Payable                           6037000000.0   5128000000.0
      Tax Payables                                808000000.0            NaN
      Deferred Revenue                           3288000000.0   3908000000.0
      Deferred Revenue                            535000000.0    599000000.0
      Other Current Liabilities                  9799000000.0   9106000000.0
      Total Current Liabilities                 64254000000.0  69300000000.0
      Long Term Debt                            14817000000.0  14701000000.0
      Deferred Tax Liabilities                   5257000000.0    514000000.0
      Other Non Current Liabilities              2205000000.0   2247000000.0
      Total Non Current Liabilities             43379000000.0  39820000000.0
      Total Liabilities                        107633000000.0 109120000000.0
      Common Stock                              61774000000.0  68184000000.0
      Retained Earnings                        191484000000.0 195563000000.0
      Accumulated Other Comprehensive Income    -1623000000.0  -7603000000.0
      Total Equity                             251635000000.0 256144000000.0
      Total Liabilities and Shareholder Equity 359268000000.0 365264000000.0
TSLA  Cash and Cash Equivalents                 17576000000.0  22185000000.0
      Short Term Investments                      131000000.0   5932000000.0
      Cash and Short Term Investments           17707000000.0  22185000000.0
      Accounts Receivable                        1913000000.0   2952000000.0
      Inventory                                  5757000000.0  12839000000.0
      Other Current Assets                                NaN   2941000000.0
      Total Current Assets                      27100000000.0  40917000000.0
      Goodwill                                    200000000.0    194000000.0
      Intangible Assets                          1717000000.0    593000000.0
      Other Fixed Assets                         2138000000.0   4193000000.0
      Fixed Assets                              35031000000.0  41421000000.0
      Total Assets                              62131000000.0  82338000000.0
      Accounts Payable                          10025000000.0  15255000000.0
      Deferred Revenue                           2372000000.0   2810000000.0
      Deferred Revenue                           2052000000.0   2804000000.0
      Other Current Liabilities                   294000000.0    354000000.0
      Total Current Liabilities                 19705000000.0  26709000000.0
      Long Term Debt                             5245000000.0   1597000000.0
      Deferred Tax Liabilities                     24000000.0     82000000.0
      Other Non Current Liabilities              3546000000.0   5330000000.0
      Total Non Current Liabilities             10843000000.0   9731000000.0
      Total Liabilities                         30548000000.0  36440000000.0
      Common Stock                                  1000000.0      3000000.0
      Retained Earnings                           331000000.0  12885000000.0
      Accumulated Other Comprehensive Income       54000000.0   -361000000.0
      Total Equity                              30189000000.0  44704000000.0
      Total Liabilities and Shareholder Equity  62131000000.0  82338000000.0
      Short Term Debt                            1589000000.0   1502000000.0

With this, it is now possible to do ratio calculations on these custom datasets. Let's have a look at the output of the extended Dupont model.

In [6]:
companies.models.get_extended_dupont_analysis()

Obtaining historical data: 100%|█████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.38it/s]

                                 2019   2020   2021   2022
GOOGL Interest Burden Ratio    0.9067 0.8574 0.8675 1.0493
      Tax Burden Ratio         0.9559 0.9768 0.9659 0.8013
      Operating Profit Margin  0.2448 0.2634 0.3522 0.2522
      Asset Turnover              NaN  0.613  0.759 0.7807
      Equity Multiplier           NaN 1.4046 1.4317 1.4269
      Return on Equity            NaN   0.19 0.3207 0.2362
TSLA  Interest Burden Ratio   -0.1203 1.7279 1.0241 1.0082
      Tax Burden Ratio        -10.775  0.346 0.8496 0.9097
      Operating Profit Margin -0.0271 0.0366 0.1178 0.1684
      Asset Turnover              NaN 0.7295  0.942 1.1277
      Equity Multiplier           NaN 2.9975 2.1803  1.929
      Return on Equity            NaN 0.0478 0.2106  0.336

This can also be extended into the area of efficiency ratios.

In [7]:
companies.ratios.collect_efficiency_ratios()

                                                   2019    2020     2021  \
GOOGL Days of Inventory Outstanding (DIO)           NaN  3.7197   3.1223
      Days of Sales Outstanding (DSO)               NaN 56.2477   49.751
      Operating Cycle (CC)                          NaN 59.9674  52.8733
      Days of Accounts Payable Outstanding (DPO)    NaN 24.0154  19.1253
      Cash Conversion Cycle (CCC)                   NaN  35.952   33.748
      Receivables Turnover                          NaN  0.1541   0.1363
      Inventory Turnover Ratio                      NaN 98.1262 116.9009
      Accounts Payable Turnover Ratio               NaN 15.1986  19.0846
      SGA-to-Revenue Ratio                       0.1731  0.1589   0.1414
      Fixed Asset Turnover                          NaN  1.3588   1.6283
      Asset Turnover Ratio                          NaN   0.613    0.759
      Operating Ratio                             0.778  0.7741   0.6945
TSLA  Days of Inventory Outstanding (DIO)           NaN 56.0778  44.7344
      Days of Sales Outstanding (DSO)               NaN 18.5764  12.8814
      Operating Cycle (CC)                          NaN 74.6541  57.6159
      Days of Accounts Payable Outstanding (DPO)    NaN 71.9712   72.951
      Cash Conversion Cycle (CCC)                   NaN  2.6829 -15.3351
      Receivables Turnover                          NaN  0.0509   0.0353
      Inventory Turnover Ratio                      NaN  6.5088   8.1593
      Accounts Payable Turnover Ratio               NaN  5.0715   5.0034
      SGA-to-Revenue Ratio                       0.1077  0.0997   0.0839
      Fixed Asset Turnover                          NaN   1.324   1.7804
      Asset Turnover Ratio                          NaN  0.7295    0.942
      Operating Ratio                            0.9967  0.9368   0.8793

                                                    2022
GOOGL Days of Inventory Outstanding (DIO)          5.553
      Days of Sales Outstanding (DSO)            51.3374
      Operating Cycle (CC)                       56.8904
      Days of Accounts Payable Outstanding (DPO) 16.1455
      Cash Conversion Cycle (CCC)                40.7448
      Receivables Turnover                        0.1407
      Inventory Turnover Ratio                   65.7307
      Accounts Payable Turnover Ratio            22.6069
      SGA-to-Revenue Ratio                        0.1495
      Fixed Asset Turnover                        1.5223
      Asset Turnover Ratio                        0.7807
      Operating Ratio                             0.7354
TSLA  Days of Inventory Outstanding (DIO)        55.9945
      Days of Sales Outstanding (DSO)            10.8991
      Operating Cycle (CC)                       66.8936
      Days of Accounts Payable Outstanding (DPO) 76.1207
      Cash Conversion Cycle (CCC)                -9.2271
      Receivables Turnover                        0.0299
      Inventory Turnover Ratio                    6.5185
      Accounts Payable Turnover Ratio              4.795
      SGA-to-Revenue Ratio                        0.0484
      Fixed Asset Turnover                        2.1311
      Asset Turnover Ratio                        1.1277
      Operating Ratio                             0.8302

Optional parameters can also be used, as an example to see the growth of each item in the financial statement.

In [8]:
companies.get_balance_sheet_statement(growth=True)

                                                2019     2020    2021    2022
      Breakdown
GOOGL Cash and Cash Equivalents                  NaN   0.4307 -0.2086  0.0446
      Short Term Investments                     NaN   0.0895  0.0769 -0.2259
      Cash and Short Term Investments            NaN   0.1422  0.0216 -0.1854
      Accounts Receivable                        NaN   0.2213  0.2707  0.0243
      Inventory                                  NaN  -0.2713  0.6071  1.2821
      Other Current Assets                       NaN   0.2443  0.2849   0.149
      Total Current Assets                       NaN   0.1423  0.0794 -0.1241
      Long Term Investments                      NaN    0.583  0.4273  0.0319
      Goodwill                                   NaN   0.0267  0.0841  0.2615
      Intangible Assets                          NaN  -0.2698 -0.0194  0.4707
      Other Fixed Assets                         NaN   0.6879  0.3562  0.2354
      Fixed Assets                               NaN   0.1783  0.1776  0.1715
      Total Assets                               NaN   0.1584  0.1241  0.0167
      Accounts Payable                           NaN    0.005  0.0802 -0.1506
      Tax Payables                               NaN   4.4197 -0.4559  5.3465
      Deferred Revenue                           NaN   0.3328   0.293  0.1886
      Deferred Revenue                           NaN   0.3436  0.1123  0.1196
      Other Current Liabilities                  NaN   0.1068 -0.0586 -0.0707
      Total Current Liabilities                  NaN   0.2568  0.1306  0.0785
      Long Term Debt                             NaN   2.0593  0.0635 -0.0078
      Deferred Tax Liabilities                   NaN   1.0935  0.4763 -0.9022
      Other Non Current Liabilities              NaN  -0.1046 -0.0282   0.019
      Total Non Current Liabilities              NaN   0.3758  0.0781  -0.082
      Total Liabilities                          NaN   0.3036  0.1088  0.0138
      Common Stock                               NaN   0.1574  0.0558  0.1038
      Retained Earnings                          NaN   0.0741  0.1719  0.0213
      Accumulated Other Comprehensive Income     NaN  -1.5138  -3.564  3.6845
      Total Equity                               NaN   0.1048  0.1307  0.0179
      Total Liabilities and Shareholder Equity   NaN   0.1584  0.1241  0.0167
TSLA  Cash and Cash Equivalents                  NaN   2.0925 -0.0933  0.2622
      Short Term Investments                     NaN   2.0925 -0.9932 44.2824
      Cash and Short Term Investments            NaN   2.0925 -0.0865  0.2529
      Accounts Receivable                        NaN   0.4245  0.0143  0.5431
      Inventory                                  NaN   0.1546  0.4038  1.2302
      Other Current Assets                       NaN   0.1546  0.4038 -0.4891
      Total Current Assets                       NaN   1.2075  0.0143  0.5099
      Goodwill                                   NaN   0.0455 -0.0338   -0.03
      Intangible Assets                          NaN  -0.0767  4.4856 -0.6546
      Other Fixed Assets                         NaN   0.4262  0.3919  0.9612
      Fixed Assets                               NaN   0.1452  0.3775  0.1824
      Total Assets                               NaN     0.52  0.1914  0.3252
      Accounts Payable                           NaN   0.6046  0.6568  0.5217
      Deferred Revenue                           NaN   0.1699  0.0733  0.1847
      Deferred Revenue                           NaN   0.0638  0.5981  0.3665
      Other Current Liabilities                  NaN  -0.2397  0.2199  0.2041
      Total Current Liabilities                  NaN   0.3357   0.383  0.3554
      Long Term Debt                             NaN  -0.1742  -0.454 -0.6955
      Deferred Tax Liabilities                   NaN   -0.987 -0.8411  2.4167
      Other Non Current Liabilities              NaN   0.2375  0.0649  0.5031
      Total Non Current Liabilities              NaN  -0.0844 -0.2375 -0.1026
      Total Liabilities                          NaN   0.0866   0.073  0.1929
      Common Stock                               NaN      inf     0.0     2.0
      Retained Earnings                          NaN  -0.1124 -1.0613 37.9275
      Accumulated Other Comprehensive Income     NaN -11.0833 -0.8512 -7.6852
      Total Equity                               NaN   2.3583  0.3583  0.4808
      Total Liabilities and Shareholder Equity   NaN     0.52  0.1914  0.3252
      Short Term Debt                            NaN   0.1944 -0.2547 -0.0548

And lastly, the historical data can be viewed.

In [9]:
companies.get_historical_data()

             Open                      High                      Low          \
             TSLA   GOOGL Benchmark    TSLA   GOOGL Benchmark   TSLA   GOOGL
Date
2014-01-02 9.9867 27.9144   1845.86 10.1653 27.9717   1845.86   9.77 27.7342
2014-01-03   10.0 27.9029   1833.21  10.146 27.9512   1838.24 9.9067 27.6509
2014-01-06   10.0 27.8531 1832.3101 10.0267 27.9995   1837.16 9.6827 27.6887
2014-01-07 9.8413 28.1532   1828.71 10.0267 28.5208    1840.1 9.6833 28.0571
2014-01-08 9.9233 28.6787    1837.9 10.2467 28.7117   1840.02 9.9173 28.3606
...           ...     ...       ...     ...     ...       ...    ...     ...
2023-10-09 255.31  136.94   4289.02  261.36  138.94   4341.73 252.05  135.61
2023-10-10 257.75   138.5   4339.75  268.94  139.72   4385.46 257.65  137.33
2023-10-11  266.2  138.58 4366.5898   268.6  141.11 4378.6401  260.9  138.58
2023-10-12 262.92  141.05 4380.9399  265.41  141.22 4385.8501 256.63  138.26
2023-10-13  258.9  139.38 4360.4902   259.6   140.0 4377.1001 250.22  136.62

                       Close  ... Volatility Excess Return                    \
           Benchmark    TSLA  ...  Benchmark          TSLA   GOOGL Benchmark
Date                          ...
2014-01-02   1827.74 10.0067  ...     0.0112        -0.032 -0.0366   -0.0387
2014-01-03   1829.13  9.9707  ...     0.0112       -0.0336 -0.0373   -0.0303
2014-01-06   1823.73     9.8  ...     0.0112       -0.0467 -0.0185   -0.0321
2014-01-07   1828.71  9.9573  ...     0.0112       -0.0133 -0.0101   -0.0233
2014-01-08    1831.4 10.0853  ...     0.0112        -0.017 -0.0278   -0.0301
...              ...     ...  ...        ...           ...     ...       ...
2023-10-09   4283.79  259.67  ...     0.0112       -0.0513 -0.0419   -0.0417
2023-10-10 4339.6401  263.62  ...     0.0112       -0.0314 -0.0492   -0.0414
2023-10-11 4345.3398  262.99  ...     0.0112       -0.0484  -0.028   -0.0417
2023-10-12 4325.4302  258.87  ...     0.0112       -0.0628 -0.0583   -0.0533
2023-10-13 4311.9702  251.12  ...     0.0112       -0.0762 -0.0579   -0.0513

           Excess Volatility                  Cumulative Return         \
                        TSLA  GOOGL Benchmark              TSLA  GOOGL
Date
2014-01-02            0.0366 0.0196    0.0142               1.0    1.0
2014-01-03            0.0366 0.0196    0.0142            0.9964 0.9927
2014-01-06            0.0366 0.0196    0.0142            0.9793 1.0038
2014-01-07            0.0366 0.0196    0.0142            0.9951 1.0231
2014-01-08            0.0366 0.0196    0.0142            1.0079 1.0253
...                      ...    ...       ...               ...    ...
2023-10-09            0.0366 0.0196    0.0142           25.9497 4.9692
2023-10-10            0.0366 0.0196    0.0142           26.3444 4.9562
2023-10-11            0.0366 0.0196    0.0142           26.2815 5.0456
2023-10-12            0.0366 0.0196    0.0142           25.8698 4.9889
2023-10-13            0.0366 0.0196    0.0142           25.0953 4.9311


           Benchmark
Date
2014-01-02       1.0
2014-01-03    0.9997
2014-01-06    0.9972
2014-01-07    1.0032
2014-01-08     1.003
...              ...
2023-10-09    2.3667
2023-10-10     2.379
2023-10-11    2.3892
2023-10-12    2.3743
2023-10-13    2.3624

[2463 rows x 36 columns]

Note that it is possible that your dataset doesn't cover all financial statement items if your normalization files are incomplete. This will become apparent when some ratios can not be calculated.

In [10]:
# Missing column returns an empty series
display(companies.ratios.get_debt_to_assets_ratio())

# Missing column skips the ratio in the total overview
display(companies.ratios.collect_profitability_ratios())

There is an index name missing in the provided financial statements. This is 'Total Debt'. This is required for the function (get_debt_to_assets_ratio) to run. Please fill this column to be able to calculate the ratios.

Series([], dtype: object)

There is an index name missing in the provided financial statements. This is 'Depreciation and Amortization'. This is required for the function (get_interest_coverage_ratio) to run. Please fill this column to be able to calculate the ratios.
There is an index name missing in the provided financial statements. This is 'Dividends Paid'. This is required for the function (get_return_on_invested_capital) to run. Please fill this column to be able to calculate the ratios.

                                                     2019   2020   2021   2022
GOOGL Gross Margin                                 0.5558 0.5358 0.5694 0.5538
      Operating Margin                              0.222 0.2259 0.3055 0.2646
      Net Profit Margin                            0.2122 0.2206 0.2951  0.212
      Income Before Tax Profit Margin              0.2448 0.2634 0.3522 0.2522
      Effective Tax Rate                           0.1333 0.1625  0.162 0.1592
      Return on Assets (ROA)                          NaN 0.1352  0.224 0.1655
      Return on Equity (ROE)                          NaN   0.19 0.3207 0.2362
      Return on Capital Employed (ROCE)            0.1722 0.1835 0.3087 0.2422
      Return on Tangible Assets                       NaN 0.1045 0.1715  0.127
      Income Quality Ratio                         1.5875 1.6172 1.2054 1.5256
      Net Income per EBT                           0.8667 0.8375  0.838 0.8408
      Free Cash Flow to Operating Cash Flow Ratio  0.5681 0.6579 0.7312 0.6559
      EBT to EBIT Ratio                            0.9975 0.9972 0.9962  0.995
      EBIT to Revenue                              0.2454 0.2642 0.3535 0.2535
TSLA  Gross Margin                                 0.1656 0.2102 0.2528  0.256
      Operating Margin                             0.0033 0.0632 0.1207 0.1698
      Net Profit Margin                           -0.0351 0.0219 0.1025 0.1545
      Income Before Tax Profit Margin             -0.0271 0.0366 0.1178 0.1684
      Effective Tax Rate                          -0.1654  0.253 0.1102 0.0825
      Return on Assets (ROA)                          NaN  0.016 0.0966 0.1742
      Return on Equity (ROE)                          NaN 0.0478 0.2106  0.336
      Return on Capital Employed (ROCE)           -0.0028 0.0456 0.1553   0.25
      Return on Tangible Assets                       NaN 0.0097  0.063 0.1177
      Income Quality Ratio                          -2.79  8.613 2.0832 1.1702
      Net Income per EBT                           1.1463 0.7026 0.8876 0.9175
      Free Cash Flow to Operating Cash Flow Ratio  0.4025 0.4545 0.3029 0.5129
      EBT to EBIT Ratio                           11.2239 0.5676 0.9437 0.9863
      EBIT to Revenue                             -0.0027 0.0549 0.1224 0.1707

Note that it is also possible to still include your Financial Modeling Prep key and run the related functionality.

In [14]:
# initialize the Toolkit
companies = Toolkit(
    tickers=["TSLA", "GOOGL"],
    balance=balance_sheets,
    income=income_statements,
    cash=cash_flow_statements,
    api_key= "2651e02dd0c5e229c372080ee1b5f6d4",
    format_location="external_datasets",
    reverse_dates=True, # Important when the dates are descending
) 

# Show the Analyst Estimates from Financial Modeling Prep
companies.get_analyst_estimates()

Obtaining analyst estimates: 100%|███████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.27s/it]

date                                        2005          2006          2007  \
TSLA  Estimated Revenue Low                  NaN           NaN           NaN
      Estimated Revenue High                 NaN           NaN           NaN
      Estimated Revenue Average              NaN           NaN           NaN
      Estimated EBITDA Low                   NaN           NaN           NaN
      Estimated EBITDA High                  NaN           NaN           NaN
      Estimated EBITDA Average               NaN           NaN           NaN
      Estimated EBIT Low                     NaN           NaN           NaN
      Estimated EBIT High                    NaN           NaN           NaN
      Estimated EBIT Average                 NaN           NaN           NaN
      Estimated Net Income Low               NaN           NaN           NaN
      Estimated Net Income High              NaN           NaN           NaN
      Estimated Net Income Average           NaN           NaN           NaN
      Estimated SGA Expense Low              NaN           NaN           NaN
      Estimated SGA Expense High             NaN           NaN           NaN
      Estimated SGA Expense Average          NaN           NaN           NaN
      Estimated EPS Average                  NaN           NaN           NaN
      Estimated EPS High                     NaN           NaN           NaN
      Estimated EPS Low                      NaN           NaN           NaN
      Number of Analysts                     NaN           NaN           NaN
GOOGL Estimated Revenue Low         4795028351.0  7538608512.0 12846722691.0
      Estimated Revenue High        7192542528.0 11307912769.0 19270084038.0
      Estimated Revenue Average     5993785440.0  9423260641.0 16058403365.0
      Estimated EBITDA Low          1766333438.0  3259059033.0  5132835931.0
      Estimated EBITDA High         2649500156.0  4888588550.0  7699253897.0
      Estimated EBITDA Average      2207916797.0  4073823792.0  6416044914.0
      Estimated EBIT Low            1451795663.0  2524574534.0  3925792375.0
      Estimated EBIT High           2177693495.0  3786861803.0  5888688564.0
      Estimated EBIT Average        1814744579.0  3155718169.0  4907240470.0
      Estimated Net Income Low      1037249172.0  2190405129.0  3246613063.0
      Estimated Net Income High     1555873759.0  3285607694.0  4869919595.0
      Estimated Net Income Average  1296561466.0  2738006412.0  4058266329.0
      Estimated SGA Expense Low      715208252.0  1136146479.0  2125617379.0
      Estimated SGA Expense High    1072812378.0  1704219721.0  3188426069.0
      Estimated SGA Expense Average  894010315.0  1420183100.0  2657021724.0
      Estimated EPS Average                 0.12          0.21         0.365
      Estimated EPS High                    0.15          0.26          0.44
      Estimated EPS Low                     0.09          0.16          0.29
      Number of Analysts                    19.0          19.0          15.0

date                                         2008          2009          2010  \
TSLA  Estimated Revenue Low                   NaN           NaN           NaN
      Estimated Revenue High                  NaN           NaN           NaN
      Estimated Revenue Average               NaN           NaN           NaN
      Estimated EBITDA Low                    NaN           NaN           NaN
      Estimated EBITDA High                   NaN           NaN           NaN
      Estimated EBITDA Average                NaN           NaN           NaN
      Estimated EBIT Low                      NaN           NaN           NaN
      Estimated EBIT High                     NaN           NaN           NaN
      Estimated EBIT Average                  NaN           NaN           NaN
      Estimated Net Income Low                NaN           NaN           NaN
      Estimated Net Income High               NaN           NaN           NaN
      Estimated Net Income Average            NaN           NaN           NaN
      Estimated SGA Expense Low               NaN           NaN           NaN
      Estimated SGA Expense High              NaN           NaN           NaN
      Estimated SGA Expense Average           NaN           NaN           NaN
      Estimated EPS Average                   NaN           NaN           NaN
      Estimated EPS High                      NaN           NaN           NaN
      Estimated EPS Low                       NaN           NaN           NaN
      Number of Analysts                      NaN           NaN           NaN
GOOGL Estimated Revenue Low         16935795486.0 17777421004.0 22007679743.0
      Estimated Revenue High        25403693230.0 26666131507.0 33011519616.0
      Estimated Revenue Average     21169744358.0 22221776256.0 27509599680.0
      Estimated EBITDA Low           5709924625.0  7448649285.0  9146367002.0
      Estimated EBITDA High          8564886940.0 11172973929.0 13719550505.0
      Estimated EBITDA Average       7137405783.0  9310811607.0 11432958754.0
      Estimated EBIT Low             5152576710.0  6248680025.0  7794504458.0
      Estimated EBIT High            7728865067.0  9373020039.0 11691756689.0
      Estimated EBIT Average         6440720889.0  7810850032.0  9743130574.0
      Estimated Net Income Low       3280005953.0  4901681757.0  6370643441.0
      Estimated Net Income High      4920008930.0  7352522638.0  9555965162.0
      Estimated Net Income Average   4100007442.0  6127102198.0  7963304302.0
      Estimated SGA Expense Low      2915388561.0  2744806910.0  3567964450.0
      Estimated SGA Expense High     4373082844.0  4117210365.0  5351946676.0
      Estimated SGA Expense Average  3644235703.0  3431008638.0  4459955563.0
      Estimated EPS Average                 0.465          0.51         0.655
      Estimated EPS High                     0.56          0.61          0.78
      Estimated EPS Low                      0.37          0.41          0.53
      Number of Analysts                     15.0          12.0          17.0

date                                         2011          2012          2013  \
TSLA  Estimated Revenue Low           168535601.0   283025277.0  1054760726.0
      Estimated Revenue High          252803404.0   424537917.0  1582141089.0
      Estimated Revenue Average       210669503.0   353781597.0  1318450908.0
      Estimated EBITDA Low           -285440842.0  -410191151.0    59070824.0
      Estimated EBITDA High          -190293894.0  -273460767.0    91129873.0
      Estimated EBITDA Average       -237867368.0  -341825959.0    75100349.0
      Estimated EBIT Low             -302817561.0  -438900935.0   -88039913.0
      Estimated EBIT High            -201878373.0  -292600623.0   -58693274.0
      Estimated EBIT Average         -252347967.0  -365750779.0   -73366594.0
      Estimated Net Income Low       -306563616.0  -441255572.0  -146837816.0
      Estimated Net Income High      -204375743.0  -294170381.0   -90393210.0
      Estimated Net Income Average   -255469680.0  -367712977.0  -118615513.0
      Estimated SGA Expense Low        84563912.0   109768700.0   269102394.0
      Estimated SGA Expense High      126845868.0   164653052.0   403653592.0
      Estimated SGA Expense Average   105704890.0   137210876.0   336377993.0
      Estimated EPS Average                 -2.27         -2.86        -0.245
      Estimated EPS High                    -1.81         -2.29          -0.1
      Estimated EPS Low                     -2.73         -3.43         -0.39
      Number of Analysts                     14.0          11.0          13.0
GOOGL Estimated Revenue Low         29466994179.0 41132626276.0 44467442531.0
      Estimated Revenue High        44200491269.0 61698939414.0 66701163797.0
      Estimated Revenue Average     36833742724.0 51415782845.0 55584303164.0
      Estimated EBITDA Low          11021106675.0 13326438074.0 15665803940.0
      Estimated EBITDA High         16531660012.0 19989657114.0 23498705910.0
      Estimated EBITDA Average      13776383344.0 16658047594.0 19582254925.0
      Estimated EBIT Low             9132981244.0 10359013879.0 11155195557.0
      Estimated EBIT High           13699471866.0 15538520818.0 16732793336.0
      Estimated EBIT Average        11416226555.0 12948767349.0 13943994447.0
      Estimated Net Income Low       7530082259.0  8699257353.0 10193364145.0
      Estimated Net Income High     11295123390.0 13048886031.0 15290046219.0
      Estimated Net Income Average   9412602825.0 10874071692.0 12741705182.0
      Estimated SGA Expense Low      6086678472.0  8229594382.0 10316882529.0
      Estimated SGA Expense High     9130017708.0 12344391573.0 15475323794.0
      Estimated SGA Expense Average  7608348090.0 10286992978.0 12896103162.0
      Estimated EPS Average                  0.86         1.045           1.1
      Estimated EPS High                     1.03          1.26          1.32
      Estimated EPS Low                      0.69          0.83          0.88
      Number of Analysts                     15.0           9.0          19.0

date                                         2014          2015  \
TSLA  Estimated Revenue Low          2803272259.0  2744149884.0
      Estimated Revenue High         4204908390.0  4116224827.0
      Estimated Revenue Average      3504090325.0  3430187356.0
      Estimated EBITDA Low             67202937.0 -1790598161.0
      Estimated EBITDA High           116549325.0 -1193732107.0
      Estimated EBITDA Average         91876131.0 -1492165134.0
      Estimated EBIT Low             -432667751.0 -3590749718.0
      Estimated EBIT High            -288445167.0 -2393833145.0
      Estimated EBIT Average         -360556459.0 -2992291432.0
      Estimated Net Income Low       -707480721.0 -4429783647.0
      Estimated Net Income High      -471653814.0 -2953189097.0
      Estimated Net Income Average   -589567268.0 -3691486372.0
      Estimated SGA Expense Low       945468432.0  2771978457.0
      Estimated SGA Expense High     1418202648.0  4157967686.0
      Estimated SGA Expense Average  1181835540.0  3464973072.0
      Estimated EPS Average                  0.75        -0.795
      Estimated EPS High                     0.92         -0.25
      Estimated EPS Low                      0.58         -1.34
      Number of Analysts                     12.0          20.0
GOOGL Estimated Revenue Low         54230365700.0 58047907489.0
      Estimated Revenue High        81345548552.0 87071861233.0
      Estimated Revenue Average     67787957126.0 72559884361.0
      Estimated EBITDA Low          18780939496.0 19198264630.0
      Estimated EBITDA High         28171409246.0 28797396948.0
      Estimated EBITDA Average      23476174371.0 23997830789.0
      Estimated EBIT Low            13552007555.0 14966768712.0
      Estimated EBIT High           20328011335.0 22450153068.0
      Estimated EBIT Average        16940009445.0 18708460890.0
      Estimated Net Income Low      11617824069.0 12621305194.0
      Estimated Net Income High     17426736105.0 18931957791.0
      Estimated Net Income Average  14522280087.0 15776631493.0
      Estimated SGA Expense Low     11489239912.0 14996937776.0
      Estimated SGA Expense High    17233859867.0 22495406665.0
      Estimated SGA Expense Average 14361549890.0 18746172221.0
      Estimated EPS Average                 1.345          1.38
      Estimated EPS High                     1.61          1.65
      Estimated EPS Low                      1.08          1.11
      Number of Analysts                     17.0          13.0

date                                          2016           2017  \
TSLA  Estimated Revenue Low           3226330592.0   9438056787.0
      Estimated Revenue High          4839495888.0  14157085182.0
      Estimated Revenue Average       4032913240.0  11797570985.0
      Estimated EBITDA Low             813638881.0    132981646.0
      Estimated EBITDA High           1334534318.0    337625225.0
      Estimated EBITDA Average        1074086600.0    235303436.0
      Estimated EBIT Low              -429111338.0  -1797932097.0
      Estimated EBIT High             -115781580.0  -1198621397.0
      Estimated EBIT Average          -272446459.0  -1498276747.0
      Estimated Net Income Low        -604415639.0  -2181290577.0
      Estimated Net Income High       -359430847.0  -1454193717.0
      Estimated Net Income Average    -481923243.0  -1817742147.0
      Estimated SGA Expense Low       1399742160.0   1872842029.0
      Estimated SGA Expense High      2099613242.0   2809263044.0
      Estimated SGA Expense Average   1749677701.0   2341052537.0
      Estimated EPS Average                 -2.705         -7.635
      Estimated EPS High                     -2.17           -6.1
      Estimated EPS Low                      -3.24          -9.17
      Number of Analysts                      14.0           20.0
GOOGL Estimated Revenue Low          72250490520.0  83521053351.0
      Estimated Revenue High        108375735780.0 125281580026.0
      Estimated Revenue Average      90313113150.0 104401316689.0
      Estimated EBITDA Low           24254021846.0  17491760180.0
      Estimated EBITDA High          36381032769.0  26237640271.0
      Estimated EBITDA Average       30317527308.0  21864700226.0
      Estimated EBIT Low             18928896440.0  19537501417.0
      Estimated EBIT High            28393344661.0  29306252125.0
      Estimated EBIT Average         23661120551.0  24421876771.0
      Estimated Net Income Low       15522946080.0   7492014868.0
      Estimated Net Income High      23284419122.0  14342751763.0
      Estimated Net Income Average   19403682601.0  10917383316.0
      Estimated SGA Expense Low      13955942982.0  14806871777.0
      Estimated SGA Expense High     20933914474.0  22210307665.0
      Estimated SGA Expense Average  17444928728.0  18508589721.0
      Estimated EPS Average                   1.72           1.42
      Estimated EPS High                      2.06           1.71
      Estimated EPS Low                       1.38           1.13
      Number of Analysts                       7.0           20.0

date                                          2018           2019  \
TSLA  Estimated Revenue Low          12867900427.0   8626233876.0
      Estimated Revenue High         19301850643.0  12939350814.0
      Estimated Revenue Average      16084875535.0  10782792345.0
      Estimated EBITDA Low           12456436555.0   5018474813.0
      Estimated EBITDA High          18884056737.0   7632302505.0
      Estimated EBITDA Average       15670246646.0   6325388659.0
      Estimated EBIT Low              3847184569.0     45613001.0
      Estimated EBIT High             6997703164.0   1266188429.0
      Estimated EBIT Average          5422443867.0    655900715.0
      Estimated Net Income Low        2099149004.0  -1433231913.0
      Estimated Net Income High       4586996630.0   -329062941.0
      Estimated Net Income Average    3343072817.0   -881147427.0
      Estimated SGA Expense Low      10421778962.0   4984100512.0
      Estimated SGA Expense High     15632668444.0   7476150770.0
      Estimated SGA Expense Average  13027223703.0   6230125641.0
      Estimated EPS Average                 -6.695         -0.535
      Estimated EPS High                     -5.16          -0.31
      Estimated EPS Low                      -8.23          -0.76
      Number of Analysts                      16.0           12.0
GOOGL Estimated Revenue Low         120690966146.0 127093991563.0
      Estimated Revenue High        181036449221.0 190640987347.0
      Estimated Revenue Average     150863707684.0 158867489455.0
      Estimated EBITDA Low           28977367529.0  38185917614.0
      Estimated EBITDA High          43466051293.0  57278876422.0
      Estimated EBITDA Average       36221709411.0  47732397018.0
      Estimated EBIT Low             16900815982.0  25737843472.0
      Estimated EBIT High            25351223973.0  38606765210.0
      Estimated EBIT Average         21126019978.0  32172304341.0
      Estimated Net Income Low       19532977824.0  25108117211.0
      Estimated Net Income High      29299466738.0  37662175817.0
      Estimated Net Income Average   24416222281.0  31385146514.0
      Estimated SGA Expense Low      17356320960.0  21149137629.0
      Estimated SGA Expense High     26034481441.0  31723706445.0
      Estimated SGA Expense Average  21695401201.0  26436422037.0
      Estimated EPS Average                   1.78          2.225
      Estimated EPS High                      2.14           2.66
      Estimated EPS Low                       1.42           1.79
      Number of Analysts                      10.0            7.0

date                                          2020           2021  \
TSLA  Estimated Revenue Low          14974798559.0  38013254905.0
      Estimated Revenue High         22462197839.0  57019882357.0
      Estimated Revenue Average      18718498199.0  47516568631.0
      Estimated EBITDA Low           15740985249.0   6222540492.0
      Estimated EBITDA High          23611477872.0   9333810739.0
      Estimated EBITDA Average       19676231561.0   7778175616.0
      Estimated EBIT Low              6292253089.0  10078959157.0
      Estimated EBIT High             9438379634.0  15118438737.0
      Estimated EBIT Average          7865316362.0  12598698947.0
      Estimated Net Income Low        1746428838.0   3641422676.0
      Estimated Net Income High       2619643259.0   5462134014.0
      Estimated Net Income Average    2183036049.0   4551778345.0
      Estimated SGA Expense Low      12365515385.0   2939271443.0
      Estimated SGA Expense High     18548273078.0   4408907166.0
      Estimated SGA Expense Average  15456894232.0   3674089305.0
      Estimated EPS Average                   0.93           4.47
      Estimated EPS High                      1.41           5.36
      Estimated EPS Low                       0.45           3.58
      Number of Analysts                       9.0           14.0
GOOGL Estimated Revenue Low         127181327012.0 192731202653.0
      Estimated Revenue High        190771990518.0 289096803980.0
      Estimated Revenue Average     158976658765.0 240914003317.0
      Estimated EBITDA Low           36199309683.0  64461779570.0
      Estimated EBITDA High          54298964526.0  96692669355.0
      Estimated EBITDA Average       45249137105.0  80577224463.0
      Estimated EBIT Low             24208375544.0  48990664306.0
      Estimated EBIT High            36312563316.0  73485996460.0
      Estimated EBIT Average         30260469430.0  61238330383.0
      Estimated Net Income Low       23401409380.0  47335069756.0
      Estimated Net Income High      35102114072.0  71002604636.0
      Estimated Net Income Average   29251761726.0  59168837196.0
      Estimated SGA Expense Low      17790419858.0  22821906759.0
      Estimated SGA Expense High     26685629788.0  34232860141.0
      Estimated SGA Expense Average  22238024823.0  28527383450.0
      Estimated EPS Average                   1.72          3.375
      Estimated EPS High                      2.07           4.05
      Estimated EPS Low                       1.37            2.7
      Number of Analysts                       7.0           18.0

date                                          2022           2023
TSLA  Estimated Revenue Low          48417704509.0  54702856529.0
      Estimated Revenue High         72626556764.0  82054284795.0
      Estimated Revenue Average      60522130637.0  68378570662.0
      Estimated EBITDA Low            8451256459.0   9503646657.0
      Estimated EBITDA High          12676884692.0  14255469991.0
      Estimated EBITDA Average       10564070576.0  11879558324.0
      Estimated EBIT Low             12587376986.0  13981202161.0
      Estimated EBIT High            18881065481.0  20971803245.0
      Estimated EBIT Average         15734221234.0  17476502703.0